### ISSUE TITLE
Doesn't run with rubicure 1.0.5+

### ISSUE THREAD

**Issue by sue445** [sue445/faker-precure#9]
https://travis-ci.org/sue445/faker-precure/jobs/251089949

```
Failures:
  1) Faker::Precure.title 
     Failure/Error: subject{ Faker::Precure.title }
     NoMethodError:
       undefined method `core' for Rubicure:Module
     # ./lib/faker/precure.rb:43:in `sample_series'
     # ./lib/faker/precure.rb:34:in `title'
     # ./spec/faker/precure_spec.rb:44:in `block (3 levels) in <top (required)>'
     # ./spec/faker/precure_spec.rb:48:in `block (3 levels) in <top (required)>'
     # /home/travis/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `load'
     # /home/travis/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
     # /home/travis/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:27:in `run'
     # /home/travis/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.15.1/lib/bundler/cli.rb:360:in `exec'
     # /home/travis/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /home/travis/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
     # /home/travis/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
     # /home/travis/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
     # /home/travis/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
     # /home/travis/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
     # /home/travis/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
     # /home/travis/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
     # /home/travis/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
```
